AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Konfigure8 SaaS Automation Platform
Parameters:
  AdminEmailParameter:
    Type: String
    Default: "matt.luthi@gmail.com"
    Description: "Enter the System Administrator email address"
  SystemAdminRoleNameParameter:
    Type: String
    Default: "SystemAdmin"
    Description: "Enter the role name for the System Administrator"
  ApiKeyOperationUsersParameter:
    Type: String
    Default: "4978c46c-aef0-4e57-9e0f-94cd33b45e22"
    Description: "Enter default API key value to be used by API Gateway for System Administrators"
  ApiKeyPlatinumTierParameter:
    Type: String
    Default: "989bb877-e514-4f50-b02e-3ae56a66b6c5"
    Description: "Enter default API key value to be used by API Gateway for Platinum Tier Tenants"
  ApiKeyPremiumTierParameter:
    Type: String
    Default: "f498a727-6d7a-4f86-b555-6b3342f3375b"
    Description: "Enter default API key value to be used by API Gateway for Premium Tier Tenants"
  ApiKeyStandardTierParameter:
    Type: String
    Default: "34c3423d-77d3-42fc-9630-d00f54a86dde"
    Description: "Enter default API key value to be used by API Gateway for Standard Tier Tenants"
  ApiKeyBasicTierParameter:
    Type: String
    Default: "c9298663-fcb0-4dce-ad9a-3f3900e2d816"
    Description: "Enter default API key value to be used by API Gateway for Basic Tier Tenants"
  StageName:
    Type: String
    Default: "prod"
    Description: "Stage Name for the API"
  LambdaCanaryDeploymentPreference:
    Type: String
    Default: "False"
    Description: "Pass it as True if you want to enable the canary release for Lambda"
  
Globals: # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: python3.10

    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true

Resources:

  DynamoDBTables:
    Type: AWS::Serverless::Application
    Properties:
      Location: k8-backend/nested-templates/tables.yaml

  Cognito:
    Type: AWS::Serverless::Application
    #DependsOn: UserInterface
    Properties:
      Location: k8-backend/nested-templates/cognito.yaml
      Parameters:
        AdminEmailParameter: !Ref AdminEmailParameter
        SystemAdminRoleNameParameter: !Ref SystemAdminRoleNameParameter
        ApiKeyOperationUsersParameter: !Ref ApiKeyOperationUsersParameter
        #AdminUserPoolCallbackURLParameter: !GetAtt UserInterface.Outputs.AdminAppSite
        #TenantUserPoolCallbackURLParameter: !GetAtt UserInterface.Outputs.ApplicationSite }

  HelloWorldFunction:
    Type: AWS::Serverless::Function     # More info about Function Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
    Properties:
      Handler: app.lambda_handler
      CodeUri: k8-backend/lambda/hello_world
      Description: Hello World function
      Architectures:
      - x86_64
      Tracing: Active
      Events:
        HelloPath:
          Type: Api           # More info about API Event Source: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-api.html
          Properties:
            Path: /hello
            Method: GET
             # Powertools for AWS Lambda (Python) env vars: https://awslabs.github.io/aws-lambda-powertools-python/#environment-variables
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: PowertoolsHelloWorld
          POWERTOOLS_METRICS_NAMESPACE: Powertools
          LOG_LEVEL: INFO
      Tags:
        LambdaPowertools: python

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod environment for Hello World Function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"

  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn

